# Generated by Django 5.2 on 2025-04-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_coursematerial_material_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField(default=5)),
                ('quiz_title', models.CharField(max_length=100, unique=True)),
                ('material_list', models.ManyToManyField(related_name='quiz_references', to='courses.coursematerial')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer_count', models.PositiveIntegerField(default=0)),
                ('incorrect_answer_count', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('t/f', 'True/False'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('correct_answer', models.CharField(max_length=50)),
                ('question_option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('question_option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('question_option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('question_option_4', models.CharField(blank=True, max_length=100, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizmodel')),
            ],
        ),
    ]
