# Generated by Django 5.2 on 2025-05-03 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_course_units_course_course_code_and_more'),
        ('quiz', '0002_quizmodel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quizmodel',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_option_1',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_option_2',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_option_3',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_option_4',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0, help_text='Current quiz score', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer')], default='MCQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddIndex(
            model_name='questionmodel',
            index=models.Index(fields=['quiz', 'question_type'], name='quiz_questi_quiz_id_207406_idx'),
        ),
        migrations.AddIndex(
            model_name='quizmodel',
            index=models.Index(fields=['course', 'quiz_title'], name='quiz_quizmo_course__9794ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizmodel',
            constraint=models.UniqueConstraint(fields=('course', 'quiz_title'), name='unique_quiz_title_per_course'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.questionmodel'),
        ),
    ]
