# Generated by Django 5.2 on 2025-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_questionmodel_correct_answer_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
