# Generated by Django 5.2 on 2025-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_questionoption_options_questionoption_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='last_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
