# Generated by Django 5.2 on 2025-05-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_quizmodel_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
