# Generated by Django 5.2 on 2025-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_questionmodel_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='questionmodel',
            name='quiz_questi_quiz_id_207406_idx',
        ),
        migrations.AddIndex(
            model_name='questionmodel',
            index=models.Index(fields=['quiz'], name='quiz_questi_quiz_id_152312_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='quiz_questi_questio_8baf09_idx'),
        ),
    ]
