# Generated by Django 5.2 on 2025-05-14 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
