# Generated by Django 5.2 on 2025-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursematerial_material_file_url'),
        ('quiz', '0006_alter_quizmodel_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='material_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_references', to='courses.coursematerial'),
        ),
    ]
