# Generated by Django 5.2 on 2025-05-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizmodel_material_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='correct_answer_count',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='incorrect_answer_count',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
