# Generated by Django 5.2 on 2025-05-21 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizmodel_last_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
