# Generated by Django 5.2 on 2025-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_coursematerial_unique_together'),
        ('quiz', '0013_quizmodel_is_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='quizmodel',
            unique_together={('course', 'quiz_title')},
        ),
    ]
