# Generated by Django 5.2 on 2025-07-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quizmodel_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='user_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
