# Generated by Django 5.2 on 2025-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_questionmodel_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='is_quick_create',
            field=models.BooleanField(default=False),
        ),
    ]
