# Generated by Django 5.2 on 2025-10-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_quizmodel_is_quick_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='is_quick_create',
        ),
    ]
