# Generated by Django 5.1.6 on 2025-02-25 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_grade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_type',
            field=models.CharField(blank=True, choices=[('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_study_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('quiz_attempts', models.PositiveIntegerField(default=0)),
                ('materials_uploaded', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_preferences', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
