# Generated by Django 5.2 on 2025-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_course_profile_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_study_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
