# Generated by Django 5.2 on 2025-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quick_create_credit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
