# Generated by Django 5.2 on 2025-09-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_quick_create_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_course',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
