# Generated by Django 5.2 on 2025-09-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_user_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
