# Generated by Django 5.2 on 2025-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_end_time_alter_course_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='material_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
