# Generated by Django 5.2 on 2025-05-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursematerial_material_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
    ]
