# Generated by Django 5.2 on 2025-05-03 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_end_time_remove_course_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='material_path',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_file',
            field=models.FileField(upload_to='course_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'jpg', 'png'])]),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course', 'uploaded_at'], name='courses_cou_course__7c91e0_idx'),
        ),
    ]
