# Generated by Django 5.2 on 2025-05-03 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_units',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
