# Generated by Django 5.2 on 2025-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_coursematerial_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
