# Generated by Django 5.2 on 2025-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_course_description_course_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_file_url',
            field=models.CharField(max_length=100),
        ),
    ]
