# Generated by Django 5.1.6 on 2025-02-25 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(choices=[('ENFP', 'ENFP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP')], max_length=4)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('target_study_hours', models.IntegerField()),
                ('current_grade', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
