# Generated by Django 5.2 on 2025-05-08 13:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_course_units_course_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='material_file',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_name',
            field=models.CharField(default="test_name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='material_file_url',
            field=models.URLField(default="https://yszhqkacyhudqdjjncjc.supabase.co/storage/v1/object/public/images//inbound1750991441972193945.webp"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(default="pdf", max_length=100),
            preserve_default=False,
        ),
    ]
