# Generated by Django 5.2 on 2025-06-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursematerial_material_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_filter', models.CharField(blank=True, max_length=100)),
                ('previous_messages', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'name_filter'], name='courses_cha_course__b13aee_idx')],
            },
        ),
    ]
