# Generated by Django 5.2 on 2025-06-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='previous_messages',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=5)),
                ('content', models.TextField()),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.chathistory')),
            ],
        ),
    ]
