# Generated by Django 5.2 on 2025-06-20 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_chathistory_previous_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
