# Generated by Django 5.2 on 2025-10-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_coursematerial_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_quick_create',
            field=models.BooleanField(default=False),
        ),
    ]
